name : Matrix

on: workflow_dispatch

jobs:
 matrix-jobs:
  runs-on: ${{matrix.os}}
  strategy:
   fail-fast: false
  include:
   - index: 0
   total: 4
   matrix:
    os: ubuntu-latest
     java: 17
     - index: 1
    os: windows-latest
     java: 21
  steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v3.14.1
      with: 
       java-version: ${{matrix.java-version}}
       distribution: microsoft
