name: Reusable Workflow

on:
 workflow_call:
 
jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - name: Checkout
     uses: action/checkout@v4.2.0
   - name: Run Reusable Build Step
     run: echo 'This is a reusbale workflow'
     
